# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bbb15b7b50f1e9ac766aa53006b567c39ea8e8793a79d1fac793233d24012e233474e16e90b444f4aee3deb9983d0e2a695a8bd1721f4d854e82afd83bc0dcb1

test:
  secret_key_base: 3016fbf7ede32c602191943bd24f9696cdce4d0ab71bc82c639b6f302a607a0728f659a118c8c38132ff073e11c745c93cf8399e7a1112bbc5b4a22f6ad56f6d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
